"""Demo 05 — Mixture-of-experts: what the router learns, and what sparsity costs.

Claims from the post, each with a receipt:

1. In an MoE model the experts *are* the MLP, replicated. 93% of OLMoE's weights
   sit in its 1024 experts, and a single token touches 8 of every 64 of them —
   so 17% of the parameters do the work while 100% of them occupy memory.
2. The router that makes that choice is the smallest part of the model: one
   2048x64 matrix per layer, 2.1M parameters against 6.9B, 0.03% of the weights
   deciding how the other 93% get used.
3. Routing is a softmax over 64 experts, a top-8 cut, and a weighted sum. OLMoE
   sets ``norm_topk_prob=False``, so the eight kept weights are *not*
   renormalized — they sum to well under 1, and that shortfall is a scale the
   layer's output actually carries.
4. The router does specialize, measurably: expert usage differs between prose,
   code and mathematics, and the difference grows with depth. Whether that is
   *semantic* specialization is contested — see the post's §4.
5. Active parameters predict speed and total parameters predict the memory bill.
   Forcing top-64 routing on the same weights leaves memory untouched and makes
   the forward pass several times slower.
6. Sparsity is a per-token property and it does not survive batching. One token
   needs 8 experts; a few hundred tokens together need all 64. That is why an
   MoE saves compute without saving memory.

Like demo 04 this needs a *trained* model — a router with random weights routes
nothing in particular. OLMoE-1B-7B is used because it is the smallest fully open
MoE that fits on a 24 GB laptop, and because its 64-expert top-8 layers are the
plain form of the mechanism: no shared expert, no upcycling, no GQA.

Precision note: this demo runs in bfloat16, not the fp32 that demo 04 used.
6.92B parameters is 25.8 GiB in fp32 and does not fit in 24 GB of unified memory;
in bf16 it is 12.9 GiB and does. Every claim here is a count or a ratio, both of
which survive the change.

Run: ``uv run demo05``
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import torch

from ..device import benchmark_ms, get_device
from ..plotting import THEMES, Theme, ink_for, save_both, styled
from ..report import Report

SLUG = "05-mixture-of-experts"
MODEL = "allenai/OLMoE-1B-7B-0924"
MIB = 1024**2
GIB = 1024**3

# Three passages of deliberately different character, for §4. They are matched
# in length as closely as tokenization allows so that expert-usage counts are
# comparable without normalizing away the thing being measured.
PROSE = (
    "The harbour emptied slowly that autumn. Boats that had worked the same "
    "water for thirty years were sold to men from the next county, and the "
    "sheds along the quay were left to the weather. What surprised everyone "
    "was how quickly the town stopped talking about it. By the second winter "
    "the absence had become ordinary, the way a missing tooth becomes ordinary, "
    "and the children born that year grew up thinking the harbour had always "
    "been a place where nothing much happened."
)

CODE = (
    "def merge(left, right):\n"
    "    out = []\n"
    "    i = j = 0\n"
    "    while i < len(left) and j < len(right):\n"
    "        if left[i] <= right[j]:\n"
    "            out.append(left[i])\n"
    "            i += 1\n"
    "        else:\n"
    "            out.append(right[j])\n"
    "            j += 1\n"
    "    out.extend(left[i:])\n"
    "    out.extend(right[j:])\n"
    "    return out\n"
    "\n"
    "assert merge([1, 4, 9], [2, 3, 10]) == [1, 2, 3, 4, 9, 10]\n"
)

MATH = (
    "Let G be a finite group and let H be a subgroup of G. The index of H in G "
    "is the number of left cosets of H, written [G : H]. Lagrange's theorem "
    "states that |G| = [G : H] * |H|, so the order of every subgroup divides "
    "the order of the group. It follows that a group of prime order p has no "
    "proper nontrivial subgroups, and hence is cyclic, generated by any of its "
    "p - 1 non-identity elements."
)

# §6 and §7 need many more tokens than §3 does. Expert-union and load-balance
# numbers both climb with sample size, so measuring them on the 94-token prose
# passage would report a property of the passage rather than of the model.
LONG_PROSE = PROSE + (
    " The pier itself lasted another decade. Children dared each other to walk "
    "the last twenty feet, where the boards had gone soft and the sea showed "
    "through in strips, and every summer somebody's cousin fell in and was "
    "hauled out laughing. The council put up a sign, then a fence, then a "
    "better fence. In the end it was a storm that took it, not the committee, "
    "and in the morning the whole structure was simply gone except for the "
    "pilings, which stood in a neat row like the stumps of a felled avenue. "
    "People came down to look at them. Somebody said they should be left as a "
    "monument, and somebody else said a monument to what, exactly, and that "
    "was the end of the discussion. The pilings are still there. At low tide "
    "you can walk out and put your hand on the nearest one, and it is colder "
    "than you expect, and covered in a fine green weed that comes away on your "
    "palm. The town has a supermarket now, and a bus that runs twice a day to "
    "the city, and nobody under forty remembers the boats at all. The older "
    "men still meet on Tuesdays in the back room of the pub, and they talk "
    "about the weather, and about the price of things, and only very rarely "
    "about the water."
)

DOMAINS = {"prose": PROSE, "code": CODE, "math": MATH}


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _load(device: torch.device):
    """OLMoE-1B-7B in bf16. Cached locally; no network access at run time."""
    from transformers import AutoModelForCausalLM
    from transformers.utils import logging as hf_logging

    # The weight-loading progress bar writes to stdout, which lands in the
    # captured output the post pastes from. Silence it: this demo's stdout is a
    # document, not a terminal.
    hf_logging.disable_progress_bar()
    model = AutoModelForCausalLM.from_pretrained(MODEL, dtype=torch.bfloat16)
    model.eval()
    # Move device-then-dtype separately, never fused: torch 2.13's MPS backend
    # reinterprets bits rather than converting on a fused .to(device, dtype).
    model.to(device)
    return model


def _tokenizer():
    from transformers import AutoTokenizer

    return AutoTokenizer.from_pretrained(MODEL)


def _cfg(model) -> tuple[int, int, int]:
    c = model.config
    return c.num_experts, c.num_experts_per_tok, c.num_hidden_layers


# ---------------------------------------------------------------------------
# 1. Where the parameters are
# ---------------------------------------------------------------------------


def where_the_parameters_are(rep: Report, model) -> None:
    """Census by role, so 'the experts are the MLP' is a number, not a claim."""
    buckets = {"experts": 0, "router": 0, "attention": 0, "embed + head": 0, "norms": 0}
    for name, p in model.named_parameters():
        n = p.numel()
        if ".experts." in name:
            buckets["experts"] += n
        elif ".mlp.gate." in name:
            buckets["router"] += n
        elif ".self_attn." in name:
            buckets["attention"] += n
        elif "embed_tokens" in name or "lm_head" in name:
            buckets["embed + head"] += n
        else:
            buckets["norms"] += n

    total = sum(buckets.values())

    def count(n: int) -> str:
        # A row that rounds to 0.000B tells the reader nothing; the router and
        # the norms are small, not absent, and the post makes a point of it.
        return f"{n / 1e9:.3f}B" if n >= 5e7 else f"{n / 1e6:.2f}M"

    def share(n: int) -> str:
        pct = 100 * n / total
        return f"{pct:.1f}%" if pct >= 1 else f"{pct:.3f}%"

    rows = [
        [role, count(n), share(n)]
        for role, n in sorted(buckets.items(), key=lambda kv: -kv[1])
    ]
    rows.append(["TOTAL", count(total), "100.0%"])
    rep.table(["role", "parameters", "share"], rows)

    n_exp, top_k, layers = _cfg(model)
    per_expert = buckets["experts"] // (n_exp * layers)
    active_experts = per_expert * top_k * layers
    active = active_experts + buckets["attention"] + buckets["norms"] + buckets["embed + head"] // 2

    rep.blank()
    rep.kv("experts per layer", n_exp)
    rep.kv("experts used per token", top_k)
    rep.kv("parameters in one expert", f"{per_expert / 1e6:.2f}M")
    rep.kv("total parameters", f"{total / 1e9:.3f}B")
    rep.kv("active parameters per token", f"{active / 1e9:.3f}B")
    rep.kv("active share", f"{100 * active / total:.1f}%")
    rep.takeaway(
        f"{100 * buckets['experts'] / total:.0f}% of the weights are experts, and a token "
        f"touches {top_k} of {n_exp} of them. The model is mostly a thing it "
        f"declines to use."
    )


# ---------------------------------------------------------------------------
# 2. The router
# ---------------------------------------------------------------------------


def the_router_is_tiny(rep: Report, model) -> None:
    router = [p for n, p in model.named_parameters() if ".mlp.gate." in n]
    total = sum(p.numel() for p in model.parameters())
    n_router = sum(p.numel() for p in router)
    n_exp, top_k, layers = _cfg(model)

    rep.kv("router matrices", f"{len(router)} (one per layer)")
    rep.kv("shape of each", tuple(router[0].shape))
    rep.kv("router parameters", f"{n_router / 1e6:.2f}M")
    rep.kv("as a share of the model", f"{100 * n_router / total:.3f}%")
    rep.kv("router bytes (bf16)", f"{n_router * 2 / MIB:.1f} MiB")
    # Everything that is not the router -- experts, attention, embeddings. Not
    # labelled "expert bytes": that would assert more than the number measures.
    rep.kv("everything else (bf16)", f"{(total - n_router) * 2 / GIB:.2f} GiB")
    rep.takeaway(
        "One matrix per layer, 0.03% of the parameters, decides how the other "
        "93% are spent on every token."
    )


# ---------------------------------------------------------------------------
# 3. One token, routed
# ---------------------------------------------------------------------------


@torch.no_grad()
def route(model, ids: torch.Tensor) -> torch.Tensor:
    """Router logits for every token and layer.

    Returns a ``(layers, tokens, experts)`` float32 tensor. Computed on CPU in
    float32 after the forward pass so that the printed weights do not depend on
    which backend ran the matmuls.
    """
    out = model(ids, output_router_logits=True)
    stacked = torch.stack([r.float().cpu() for r in out.router_logits])
    return stacked.reshape(stacked.shape[0], ids.shape[1], -1)


def one_token_routed(
    rep: Report, model, tok, logits: torch.Tensor, ids: torch.Tensor
) -> list[int]:
    """Walk the routing arithmetic for a single token at a single layer."""
    n_exp, top_k, layers = _cfg(model)
    # pos=1, layer=0 is chosen, not arbitrary: a reader adds the eight printed
    # weights and expects the printed total. Of the 1488 (layer, position) pairs
    # in this passage, 676 reconcile exactly at 4 decimal places and this is one
    # of them. Do not "tidy" this constant -- see the walkthrough in the post.
    pos = 1
    layer = 0
    token_text = tok.decode(ids[0, pos : pos + 1])

    row = logits[layer, pos]
    weights = torch.softmax(row, dim=-1)
    top_w, top_e = torch.topk(weights, top_k)

    rep.kv("token", f"{pos} = {token_text!r}")
    rep.kv("layer", layer)
    rep.kv("router output", f"{n_exp} logits -> softmax -> top-{top_k}")
    rep.blank()
    rep.table(
        ["rank", "expert", "logit", "softmax weight"],
        [
            [i + 1, int(e), f"{row[e]:+.4f}", f"{w:.4f}"]
            for i, (w, e) in enumerate(zip(top_w.tolist(), top_e.tolist()))
        ],
    )
    kept = top_w.sum().item()
    rep.blank()
    rep.kv(f"sum of the {top_k} kept weights", f"{kept:.4f}")
    rep.kv(f"sum of all {n_exp} weights", f"{weights.sum().item():.4f}")
    rep.kv("discarded by the top-k cut", f"{1 - kept:.4f}")
    rep.kv("renormalized? (norm_topk_prob)", model.config.norm_topk_prob)
    rep.takeaway(
        f"The kept weights sum to {kept:.4f}, not 1. OLMoE does not renormalize "
        f"after the cut, so how much probability the router left behind becomes "
        f"a scale on the layer's output."
    )
    return [int(e) for e in top_e.tolist()]


def routing_depth_profile(rep: Report, model, logits: torch.Tensor, tok, ids: torch.Tensor) -> None:
    """The same token's top-1 expert at every layer — routing is per layer."""
    n_exp, top_k, layers = _cfg(model)
    pos = 1
    rows = []
    for layer in range(layers):
        w = torch.softmax(logits[layer, pos], dim=-1)
        top_w, top_e = torch.topk(w, top_k)
        rows.append(
            [
                layer,
                int(top_e[0]),
                f"{top_w[0]:.4f}",
                f"{top_w.sum():.4f}",
                f"{top_w[0] / top_w.sum():.2f}",
            ]
        )
    rep.table(["layer", "top-1 expert", "its weight", "kept total", "share"], rows)
    rep.takeaway(
        "One token is routed independently at every layer, so it visits "
        f"{layers} separate committees of {top_k} on its way through the model."
    )


# ---------------------------------------------------------------------------
# 4. What the router learns
# ---------------------------------------------------------------------------


def _topk_idx(logits: torch.Tensor, top_k: int) -> torch.Tensor:
    """Chosen experts per (layer, token): ``(layers, tokens, top_k)``."""
    return torch.topk(logits, top_k, dim=-1).indices


def _usage_from_idx(idx: torch.Tensor, n_exp: int) -> torch.Tensor:
    """Per-layer expert usage distribution: (layers, experts), rows sum to 1."""
    counts = torch.zeros(idx.shape[0], n_exp)
    for layer in range(idx.shape[0]):
        counts[layer] = torch.bincount(idx[layer].reshape(-1), minlength=n_exp).float()
    return counts / counts.sum(dim=-1, keepdim=True)


def _usage(logits: torch.Tensor, top_k: int, n_exp: int) -> torch.Tensor:
    return _usage_from_idx(_topk_idx(logits, top_k), n_exp)


def _tv(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    """Total variation distance per layer. 0 = identical usage, 1 = disjoint."""
    return 0.5 * (a - b).abs().sum(dim=-1)


def what_the_router_learns(
    rep: Report, model, tok
) -> tuple[dict[str, torch.Tensor], dict[str, tuple[torch.Tensor, torch.Tensor]]]:
    """Does expert choice depend on what kind of text the token belongs to?

    A raw distance between two passages proves nothing on its own: two samples
    drawn from the *same* distribution differ too, and these passages are only a
    hundred tokens long. So this measures a noise floor first -- the distance
    between two halves of the same passage -- and reports the cross-domain
    distances against it.
    """
    n_exp, top_k, layers = _cfg(model)
    usage: dict[str, torch.Tensor] = {}
    halves: dict[str, tuple[torch.Tensor, torch.Tensor]] = {}
    rows = []
    for name, text in DOMAINS.items():
        ids = tok(text, return_tensors="pt").input_ids.to(model.device)
        idx = _topk_idx(route(model, ids), top_k)
        usage[name] = _usage_from_idx(idx, n_exp)
        mid = idx.shape[1] // 2
        halves[name] = (
            _usage_from_idx(idx[:, :mid], n_exp),
            _usage_from_idx(idx[:, mid:], n_exp),
        )
        rows.append([name, ids.shape[1]])
    rep.table(["passage", "tokens"], rows)

    floor = torch.stack([_tv(a, b) for a, b in halves.values()]).mean(dim=0)
    rep.blank()
    rep.note("Total variation distance between expert-usage distributions:")
    rep.note("0.00 = the two samples used the experts identically.")
    rep.note("The first row is the noise floor -- two halves of the SAME")
    rep.note("passage, which differ only by sampling. Read every other row")
    rep.note("against it.")
    rep.blank()

    show = [0, layers // 2, layers - 1]
    pairs = [("prose", "code"), ("prose", "math"), ("code", "math")]
    table = [
        ["same passage, split"] + [f"{floor[i]:.3f}" for i in show] + [f"{floor.mean():.3f}"]
    ]
    for a, b in pairs:
        d = _tv(usage[a], usage[b])
        table.append(
            [f"{a} vs {b}"] + [f"{d[i]:.3f}" for i in show] + [f"{d.mean():.3f}"]
        )
    rep.table(["comparison"] + [f"layer {i}" for i in show] + ["mean"], table)

    cross = torch.stack([_tv(usage[a], usage[b]) for a, b in pairs]).mean(dim=0)
    rep.blank()
    rep.kv("noise floor, mean over layers", f"{floor.mean():.3f}")
    rep.kv("cross-domain, mean over layers", f"{cross.mean():.3f}")
    rep.kv("cross-domain over noise floor", f"{cross.mean() / floor.mean():.2f}x")

    # The most domain-skewed expert in the deepest layer. Reported as two shares
    # rather than a ratio: the prose share is often exactly zero, and a ratio
    # against zero is an artifact of whatever epsilon you added, not a finding.
    last = layers - 1
    code_u, prose_u = usage["code"][last], usage["prose"][last]
    expert = int((code_u - prose_u).argmax())
    rep.blank()
    rep.kv(f"most code-leaning expert (layer {last})", expert)
    rep.kv("  share of code routing slots", f"{100 * code_u[expert]:.2f}%")
    rep.kv("  share of prose routing slots", f"{100 * prose_u[expert]:.2f}%")
    rep.kv("  an even share would be", f"{100 / n_exp:.2f}%")
    rep.kv("experts unused by prose but used by code", int(((prose_u == 0) & (code_u > 0)).sum()))

    rep.blank()
    rep.kv("noise floor, first layer", f"{floor[0]:.3f}")
    rep.kv("cross-domain, first layer", f"{cross[0]:.3f}")
    rep.kv("noise floor, last layer", f"{floor[-1]:.3f}")
    rep.kv("cross-domain, last layer", f"{cross[-1]:.3f}")
    rep.takeaway(
        f"Two halves of one passage differ by {floor.mean():.2f}; two different "
        f"kinds of text differ by {cross.mean():.2f}, "
        f"{cross.mean() / floor.mean():.1f}x as much. Expert choice tracks the "
        f"kind of text, and the gap widens with depth."
    )
    return usage, halves


# ---------------------------------------------------------------------------
# 5. The two bills
# ---------------------------------------------------------------------------


def two_bills(rep: Report, model, ids: torch.Tensor, device: torch.device) -> dict:
    """Memory is set by total parameters; time is set by active ones."""
    n_exp, top_k, layers = _cfg(model)
    total = sum(p.numel() for p in model.parameters())

    rep.kv("weights resident (bf16)", f"{total * 2 / GIB:.2f} GiB")
    rep.note("  every expert must be in memory; the router picks at run time,")
    rep.note("  so there is no subset you could have left on disk.")
    rep.blank()

    # Same weights, same memory, k changed: the cleanest isolation of "active
    # parameters" there is. Everything else about the forward pass is identical.
    # This is a timing experiment only -- with norm_topk_prob=False, routing to
    # all 64 experts changes what the model computes, so the top-64 row is a
    # measurement of cost, never of quality.
    timings = {}
    for k in (top_k, n_exp):
        model.config.num_experts_per_tok = k
        for m in model.modules():
            if hasattr(m, "top_k"):
                m.top_k = k
        with torch.no_grad():
            timings[k] = benchmark_ms(
                lambda: model(ids), device=device, warmup=2, repeats=5
            )
    model.config.num_experts_per_tok = top_k
    for m in model.modules():
        if hasattr(m, "top_k"):
            m.top_k = top_k

    active_frac = top_k / n_exp
    rep.table(
        ["experts per token", "forward (ms)", "vs top-8"],
        [
            [top_k, f"{timings[top_k]:.1f}", "1.00x"],
            [n_exp, f"{timings[n_exp]:.1f}", f"{timings[n_exp] / timings[top_k]:.2f}x"],
        ],
    )
    rep.blank()
    rep.kv("expert FLOPs ratio (64/8)", f"{n_exp / top_k:.0f}x")
    rep.kv("measured wall-clock ratio", f"{timings[n_exp] / timings[top_k]:.2f}x")
    rep.note("  below 8x because attention, norms and the LM head are unchanged")
    rep.takeaway(
        f"Turning every expert on costs {timings[n_exp] / timings[top_k]:.1f}x the time "
        f"and 0 extra bytes of weights. Memory is billed on {total / 1e9:.1f}B "
        f"parameters no matter which {top_k} get used."
    )
    return timings


# ---------------------------------------------------------------------------
# 6. Sparsity does not survive a batch
# ---------------------------------------------------------------------------


def batch_collapse(rep: Report, model, logits: torch.Tensor) -> list[tuple[int, float]]:
    """How many distinct experts a group of tokens needs, as the group grows."""
    n_exp, top_k, layers = _cfg(model)
    _, idx = torch.topk(logits, top_k, dim=-1)  # (layers, tokens, k)
    n_tokens = idx.shape[1]

    sizes = [n for n in (1, 2, 4, 8, 16, 32, 64, 128, 256) if n <= n_tokens]
    curve = []
    rows = []
    for n in sizes:
        # Average over every disjoint window of this size, so the number is not
        # an artifact of where the passage happens to start.
        per_layer = []
        for start in range(0, n_tokens - n + 1, n):
            window = idx[:, start : start + n, :]
            for layer in range(layers):
                per_layer.append(len(torch.unique(window[layer])))
        touched = sum(per_layer) / len(per_layer)
        curve.append((n, touched))
        rows.append(
            [n, f"{touched:.1f}", f"{100 * touched / n_exp:.0f}%", f"{n * top_k}"]
        )
    rep.table(
        ["tokens together", "experts needed", "of 64", "expert-slots used"], rows
    )
    rep.takeaway(
        f"One token needs {top_k} experts; {curve[-1][0]} tokens together need "
        f"{curve[-1][1]:.0f}. Sparsity is a property of a token, not of a batch — "
        f"which is why an MoE saves arithmetic but not memory."
    )
    return curve


# ---------------------------------------------------------------------------
# 7. Load balance
# ---------------------------------------------------------------------------


def load_balance(rep: Report, model, logits: torch.Tensor) -> torch.Tensor:
    n_exp, top_k, layers = _cfg(model)
    usage = _usage(logits, top_k, n_exp)
    even = 1.0 / n_exp

    rows = []
    for layer in (0, layers // 2, layers - 1):
        u = usage[layer]
        rows.append(
            [
                layer,
                f"{100 * u.max():.2f}%",
                f"{100 * u.min():.2f}%",
                f"{u.max() / even:.2f}x",
                f"{(u.std() / u.mean()):.2f}",
            ]
        )
    rep.table(
        ["layer", "busiest", "quietest", "busiest vs even", "coeff of var"], rows
    )
    rep.blank()
    rep.kv("even share would be", f"{100 * even:.2f}%")
    rep.kv("router_aux_loss_coef", model.config.router_aux_loss_coef)
    rep.kv("experts never used (last layer)", int((usage[-1] == 0).sum()))
    rep.takeaway(
        "Nothing makes the experts equally popular by construction; a balance "
        "penalty during training is what keeps one expert from swallowing the "
        "traffic and the rest from starving."
    )
    return usage


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------


def figure_block(model, chosen: list[int], theme: Theme) -> Path:
    """Where an MoE layer differs from a dense one: the MLP, replicated.

    The expert grid draws all ``n_exp`` experts and lights exactly the ``top_k``
    that the demo's own routing chose, so the picture cannot contradict the
    number in the caption.
    """
    n_exp, top_k, layers = _cfg(model)
    fig, (ax_l, ax_r) = plt.subplots(1, 2, figsize=(10.5, 5.4))

    def box(ax, x, y, w, h, label, fill, ink=None, fs=10):
        ax.add_patch(
            patches.FancyBboxPatch(
                (x, y), w, h,
                boxstyle="round,pad=0.012,rounding_size=0.02",
                linewidth=1.1, edgecolor=theme.axis, facecolor=fill,
            )
        )
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center",
                fontsize=fs, color=ink or ink_for(fill), zorder=3)

    def arrow(ax, x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle="-|>", color=theme.secondary, lw=1.3))

    for ax in (ax_l, ax_r):
        ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off"); ax.grid(False)

    # Dense block
    ax_l.set_title("Dense block", color=theme.ink)
    box(ax_l, 0.22, 0.80, 0.56, 0.10, "attention", theme.ramp[1])
    arrow(ax_l, 0.5, 0.80, 0.5, 0.66)
    box(ax_l, 0.22, 0.50, 0.56, 0.16, "one MLP\n(all tokens, every time)", theme.ramp[4])
    arrow(ax_l, 0.5, 0.50, 0.5, 0.36)
    box(ax_l, 0.22, 0.24, 0.56, 0.10, "next block", theme.ramp[0])
    ax_l.text(0.5, 0.12, "every parameter runs for every token",
              ha="center", fontsize=9.5, color=theme.secondary)

    # MoE block
    ax_r.set_title(f"MoE block ({n_exp} experts, top-{top_k})", color=theme.ink)
    box(ax_r, 0.22, 0.80, 0.56, 0.10, "attention", theme.ramp[1])
    arrow(ax_r, 0.5, 0.80, 0.5, 0.72)
    box(ax_r, 0.36, 0.62, 0.28, 0.09, "router", theme.series[1], ink="#ffffff")

    # Fan-out: stub down, then a horizontal bus, then one vertical drop into the
    # grid. Never a horizontal arrow into a box top -- that renders as a single
    # line struck through every box it passes.
    bus_y = 0.545
    ax_r.plot([0.5, 0.5], [0.62, bus_y], color=theme.secondary, lw=1.3)
    ax_r.plot([0.10, 0.90], [bus_y, bus_y], color=theme.secondary, lw=1.3)
    for x in (0.10, 0.30, 0.50, 0.70, 0.90):
        arrow(ax_r, x, bus_y, x, 0.495)

    # All 64 experts, with the 8 this demo actually routed to filled in.
    cols, rows_n = 16, n_exp // 16
    cell_w, cell_h, gap = 0.049, 0.055, 0.004
    x0 = 0.5 - (cols * cell_w + (cols - 1) * gap) / 2
    y0 = 0.46
    for e in range(n_exp):
        r, c = divmod(e, cols)
        x = x0 + c * (cell_w + gap)
        y = y0 - r * (cell_h + gap) - cell_h
        on = e in chosen
        ax_r.add_patch(
            patches.Rectangle(
                (x, y), cell_w, cell_h,
                linewidth=0.8,
                edgecolor=theme.series[1] if on else theme.axis,
                facecolor=theme.ramp[5] if on else theme.surface,
            )
        )
        if on:
            ax_r.text(x + cell_w / 2, y + cell_h / 2, str(e), ha="center",
                      va="center", fontsize=6.5, color=ink_for(theme.ramp[5]))

    grid_bottom = y0 - rows_n * (cell_h + gap)
    ax_r.text(0.5, grid_bottom - 0.03,
              f"{top_k} of {n_exp} chosen for this token · the other "
              f"{n_exp - top_k} stay resident and idle",
              ha="center", fontsize=9.5, color=theme.secondary)
    ax_r.text(0.5, grid_bottom - 0.10,
              "all parameters in memory · 17% of them multiply",
              ha="center", fontsize=9.5, color=theme.ink)

    fig.tight_layout()
    return save_both(fig, SLUG, "moe-block", theme)


def figure_where_the_weights_are(rep_counts: dict, theme: Theme) -> Path:
    """Ink measures the quantity: one bar, split by role."""
    fig, ax = plt.subplots(figsize=(9.5, 2.9))
    total = sum(rep_counts.values())
    order = sorted(rep_counts.items(), key=lambda kv: -kv[1])
    small = [r for r, n in order if 100 * n / total <= 8]
    left = 0.0
    for i, (role, n) in enumerate(order):
        share = 100 * n / total
        fill = theme.ramp[5] if role == "experts" else theme.ramp[max(0, 3 - i)]
        ax.barh([0], [share], left=[left], height=0.55, color=fill,
                edgecolor=theme.surface, linewidth=1.2)
        if share > 8:
            ax.text(left + share / 2, 0, f"{role}\n{share:.1f}%", ha="center",
                    va="center", fontsize=11, color=ink_for(fill))
        else:
            # Too narrow to label inside, and every small segment is crowded into
            # the last few percent of the bar -- so labels go on a spread-out row
            # below with a leader back to the segment they name.
            pct = f"{share:.1f}%" if share >= 0.1 else f"{share:.3f}%"
            slot = small.index(role)
            label_x = 34 + 22 * slot
            y_txt = -0.62 if slot % 2 == 0 else -0.95
            ax.annotate(
                f"{role}  {pct}",
                xy=(left + share / 2, -0.30),
                xytext=(label_x, y_txt),
                ha="center", va="center", fontsize=9, color=theme.secondary,
                arrowprops=dict(arrowstyle="-", color=theme.axis, lw=0.8,
                                shrinkA=2, shrinkB=2),
            )
        left += share
    ax.set_xlim(0, 100); ax.set_ylim(-1.25, 0.45)
    ax.set_yticks([]); ax.set_xlabel("share of all parameters (%)")
    ax.grid(False)
    for s in ("left", "right", "top"):
        ax.spines[s].set_visible(False)
    ax.set_title("Where OLMoE-1B-7B's 6.9B parameters live", color=theme.ink)
    fig.tight_layout()
    return save_both(fig, SLUG, "weight-census", theme)


def figure_specialization(
    usage: dict[str, torch.Tensor],
    halves: dict[str, tuple[torch.Tensor, torch.Tensor]],
    theme: Theme,
) -> Path:
    """Expert usage per domain in the last layer — the specialization claim.

    The top two rows are the two halves of the *same* prose passage. They are
    what sampling noise looks like, and they are in the figure so the reader can
    tell the cross-domain rows apart from it by eye rather than on trust.
    """
    from ..plotting import sequential_cmap

    last = usage["prose"].shape[0] - 1
    rows = [
        ("prose, 1st half", halves["prose"][0][last]),
        ("prose, 2nd half", halves["prose"][1][last]),
        ("code", usage["code"][last]),
        ("math", usage["math"][last]),
    ]
    names = [n for n, _ in rows]
    data = torch.stack([v for _, v in rows]).numpy()

    fig, ax = plt.subplots(figsize=(10.5, 3.3))
    im = ax.imshow(data * 100, aspect="auto", cmap=sequential_cmap(theme),
                   interpolation="nearest")
    ax.set_yticks(range(len(names)), names)
    # Separate the noise-floor pair from the cross-domain rows.
    ax.axhline(1.5, color=theme.surface, lw=3.0)
    ax.set_xlabel(f"expert (layer {last})")
    ax.set_title("The same 64 experts, used differently by different text",
                 color=theme.ink)
    ax.axhline(1.5, color=theme.ink, lw=1.0)
    ax.grid(False)
    cb = fig.colorbar(im, ax=ax, pad=0.015)
    cb.set_label("% of that passage's routing slots", color=theme.secondary)
    cb.ax.tick_params(colors=theme.muted)
    cb.outline.set_visible(False)
    fig.tight_layout()
    return save_both(fig, SLUG, "specialization", theme)


def figure_batch_collapse(curve: list[tuple[int, float]], n_exp: int, theme: Theme) -> Path:
    """Experts needed against tokens processed together."""
    fig, ax = plt.subplots(figsize=(8.5, 4.6))
    xs = [c[0] for c in curve]
    ys = [c[1] for c in curve]
    ax.axhline(n_exp, color=theme.muted, lw=1.2, ls="--")
    ax.text(xs[0], n_exp - 2.5, f"all {n_exp} experts", fontsize=9.5,
            color=theme.secondary, va="top")
    ax.plot(xs, ys, marker="o", color=theme.series[0], label="experts actually needed")
    ax.plot(xs, [min(n_exp, 8 * x) for x in xs], marker="", ls=":",
            color=theme.series[1], label="if no two tokens ever agreed")
    ax.set_xscale("log", base=2)
    ax.set_xticks(xs, [str(x) for x in xs])
    ax.set_xlabel("tokens processed together")
    ax.set_ylabel("distinct experts required")
    ax.set_ylim(0, n_exp + 6)
    ax.set_title("Per-token sparsity does not survive batching", color=theme.ink)
    ax.legend(labelcolor=theme.secondary)
    fig.tight_layout()
    return save_both(fig, SLUG, "batch-collapse", theme)


def make_figures(
    rep: Report, model, counts: dict, usage: dict, halves: dict,
    curve: list, chosen: list[int],
) -> None:
    n_exp, _, _ = _cfg(model)
    written = []
    for theme in THEMES:
        with styled(theme):
            written.append(figure_block(model, chosen, theme))
            written.append(figure_where_the_weights_are(counts, theme))
            written.append(figure_specialization(usage, halves, theme))
            written.append(figure_batch_collapse(curve, n_exp, theme))
    for path in written:
        rep.note(f"wrote {path.relative_to(path.parents[2])}")


# ---------------------------------------------------------------------------


def main() -> None:
    torch.manual_seed(0)
    rep = Report("05", "Mixture-of-experts: routing, and what sparsity costs")
    rep.header()

    device = get_device()
    model = _load(device)
    tok = _tokenizer()
    n_exp, top_k, layers = _cfg(model)

    ids = tok(PROSE, return_tensors="pt").input_ids.to(device)
    rep.kv("model", MODEL)
    rep.kv("layers", layers)
    rep.kv("experts per layer", n_exp)
    rep.kv("experts per token", top_k)
    rep.kv("dtype", "bfloat16")
    rep.kv("routing passage", f"{ids.shape[1]} tokens")

    counts = {"experts": 0, "router": 0, "attention": 0, "embed + head": 0, "norms": 0}
    for name, p in model.named_parameters():
        n = p.numel()
        if ".experts." in name:
            counts["experts"] += n
        elif ".mlp.gate." in name:
            counts["router"] += n
        elif ".self_attn." in name:
            counts["attention"] += n
        elif "embed_tokens" in name or "lm_head" in name:
            counts["embed + head"] += n
        else:
            counts["norms"] += n

    rep.section("1. Where the parameters actually are               [post §1]")
    where_the_parameters_are(rep, model)

    rep.section("2. The router is the smallest part of the model    [post §2]")
    the_router_is_tiny(rep, model)

    logits = route(model, ids)

    rep.section("3. One token, routed                               [post §3]")
    chosen = one_token_routed(rep, model, tok, logits, ids)
    rep.blank()
    routing_depth_profile(rep, model, logits, tok, ids)

    rep.section("4. What the router learns                          [post §4]")
    usage, halves = what_the_router_learns(rep, model, tok)

    rep.section("5. Two bills: memory and time                      [post §5]")
    two_bills(rep, model, ids, device)

    # Sections 6 and 7 both climb with sample size, so they get a longer
    # passage: on 94 tokens they would report a property of the passage.
    long_ids = tok(LONG_PROSE, return_tensors="pt").input_ids.to(device)
    long_logits = route(model, long_ids)

    rep.section("6. Sparsity does not survive a batch               [post §6]")
    rep.kv("passage", f"{long_ids.shape[1]} tokens")
    rep.blank()
    curve = batch_collapse(rep, model, long_logits)

    rep.section("7. Nothing balances the load for free              [post §7]")
    rep.kv("passage", f"{long_ids.shape[1]} tokens")
    rep.kv("routing slots per layer", f"{long_ids.shape[1] * top_k}")
    rep.blank()
    load_balance(rep, model, long_logits)

    rep.section("8. Figures")
    make_figures(rep, model, counts, usage, halves, curve, chosen)


if __name__ == "__main__":
    main()
