"""Demo 05 — Mixture-of-experts: what the router learns, and what sparsity costs.

Claims from the post, each with a receipt:

1. In an MoE model the experts *are* the MLP, replicated. 93% of OLMoE's weights
   sit in its 1024 experts, and a single token touches 8 of every 64 of them —
   so 17% of the parameters do the work while 100% of them occupy memory.
2. The router that makes that choice is the smallest part of the model: one
   2048x64 matrix per layer, 2.1M parameters against 6.9B, 0.03% of the weights
   deciding how the other 93% get used.
3. Routing is a softmax over 64 experts, a top-8 cut, and a weighted sum. OLMoE
   sets ``norm_topk_prob=False``, so the eight kept weights are *not*
   renormalized — they sum to well under 1, and that shortfall is a scale the
   layer's output actually carries.
4. The router does specialize, measurably: expert usage differs between prose,
   code and mathematics, and the difference grows with depth. Whether that is
   *semantic* specialization is contested — see the post's §4.
5. Active parameters predict speed and total parameters predict the memory bill.
   Forcing top-64 routing on the same weights leaves memory untouched and makes
   the forward pass several times slower.
6. Sparsity is a per-token property and it does not survive batching. One token
   needs 8 experts; a few hundred tokens together need all 64. That is why an
   MoE saves compute without saving memory.

Like demo 04 this needs a *trained* model — a router with random weights routes
nothing in particular. OLMoE-1B-7B is used because it is the smallest fully open
MoE that fits on a 24 GB laptop, and because its 64-expert top-8 layers are the
plain form of the mechanism: no shared expert, no upcycling, no GQA.

Precision note: this demo runs in bfloat16, not the fp32 that demo 04 used.
6.92B parameters is 25.8 GiB in fp32 and does not fit in 24 GB of unified memory;
in bf16 it is 12.9 GiB and does. Every claim here is a count or a ratio, both of
which survive the change.

Run: ``uv run demo05``
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import torch

from ..device import benchmark_ms, get_device
from ..plotting import THEMES, Theme, ink_for, save_both, styled
from ..report import Report

SLUG = "05-mixture-of-experts"
MODEL = "allenai/OLMoE-1B-7B-0924"
MIB = 1024**2
GIB = 1024**3

# Three passages of deliberately different character, for §4. They are matched
# in length as closely as tokenization allows so that expert-usage counts are
# comparable without normalizing away the thing being measured.
PROSE = (
    "The harbour emptied slowly that autumn. Boats that had worked the same "
    "water for thirty years were sold to men from the next county, and the "
    "sheds along the quay were left to the weather. What surprised everyone "
    "was how quickly the town stopped talking about it. By the second winter "
    "the absence had become ordinary, the way a missing tooth becomes ordinary, "
    "and the children born that year grew up thinking the harbour had always "
    "been a place where nothing much happened."
)

CODE = (
    "def merge(left, right):\n"
    "    out = []\n"
    "    i = j = 0\n"
    "    while i < len(left) and j < len(right):\n"
    "        if left[i] <= right[j]:\n"
    "            out.append(left[i])\n"
    "            i += 1\n"
    "        else:\n"
    "            out.append(right[j])\n"
    "            j += 1\n"
    "    out.extend(left[i:])\n"
    "    out.extend(right[j:])\n"
    "    return out\n"
    "\n"
    "assert merge([1, 4, 9], [2, 3, 10]) == [1, 2, 3, 4, 9, 10]\n"
)

MATH = (
    "Let G be a finite group and let H be a subgroup of G. The index of H in G "
    "is the number of left cosets of H, written [G : H]. Lagrange's theorem "
    "states that |G| = [G : H] * |H|, so the order of every subgroup divides "
    "the order of the group. It follows that a group of prime order p has no "
    "proper nontrivial subgroups, and hence is cyclic, generated by any of its "
    "p - 1 non-identity elements."
)

# §6 and §7 need many more tokens than §3 does. Expert-union and load-balance
# numbers both climb with sample size, so measuring them on the 94-token prose
# passage would report a property of the passage rather than of the model.
LONG_PROSE = PROSE + (
    " The pier itself lasted another decade. Children dared each other to walk "
    "the last twenty feet, where the boards had gone soft and the sea showed "
    "through in strips, and every summer somebody's cousin fell in and was "
    "hauled out laughing. The council put up a sign, then a fence, then a "
    "better fence. In the end it was a storm that took it, not the committee, "
    "and in the morning the whole structure was simply gone except for the "
    "pilings, which stood in a neat row like the stumps of a felled avenue. "
    "People came down to look at them. Somebody said they should be left as a "
    "monument, and somebody else said a monument to what, exactly, and that "
    "was the end of the discussion. The pilings are still there. At low tide "
    "you can walk out and put your hand on the nearest one, and it is colder "
    "than you expect, and covered in a fine green weed that comes away on your "
    "palm. The town has a supermarket now, and a bus that runs twice a day to "
    "the city, and nobody under forty remembers the boats at all. The older "
    "men still meet on Tuesdays in the back room of the pub, and they talk "
    "about the weather, and about the price of things, and only very rarely "
    "about the water."
)

DOMAINS = {"prose": PROSE, "code": CODE, "math": MATH}


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _load(device: torch.device):
    """OLMoE-1B-7B in bf16. Cached locally; no network access at run time."""
    from transformers import AutoModelForCausalLM
    from transformers.utils import logging as hf_logging

    # The weight-loading progress bar writes to stdout, which lands in the
    # captured output the post pastes from. Silence it: this demo's stdout is a
    # document, not a terminal.
    hf_logging.disable_progress_bar()
    model = AutoModelForCausalLM.from_pretrained(MODEL, dtype=torch.bfloat16)
    model.eval()
    # Move device-then-dtype separately, never fused: torch 2.13's MPS backend
    # reinterprets bits rather than converting on a fused .to(device, dtype).
    model.to(device)
    return model


def _tokenizer():
    from transformers import AutoTokenizer

    return AutoTokenizer.from_pretrained(MODEL)


def _cfg(model) -> tuple[int, int, int]:
    c = model.config
    return c.num_experts, c.num_experts_per_tok, c.num_hidden_layers


# ---------------------------------------------------------------------------
# 1. Where the parameters are
# ---------------------------------------------------------------------------


def where_the_parameters_are(rep: Report, model) -> None:
    """Census by role, so 'the experts are the MLP' is a number, not a claim."""
    buckets = {"experts": 0, "router": 0, "attention": 0, "embed + head": 0, "norms": 0}
    for name, p in model.named_parameters():
        n = p.numel()
        if ".experts." in name:
            buckets["experts"] += n
        elif ".mlp.gate." in name:
            buckets["router"] += n
        elif ".self_attn." in name:
            buckets["attention"] += n
        elif "embed_tokens" in name or "lm_head" in name:
            buckets["embed + head"] += n
        else:
            buckets["norms"] += n

    total = sum(buckets.values())

    def count(n: int) -> str:
        # A row that rounds to 0.000B tells the reader nothing; the router and
        # the norms are small, not absent, and the post makes a point of it.
        return f"{n / 1e9:.3f}B" if n >= 5e7 else f"{n / 1e6:.2f}M"

    def share(n: int) -> str:
        pct = 100 * n / total
        return f"{pct:.1f}%" if pct >= 1 else f"{pct:.3f}%"

    rows = [
        [role, count(n), share(n)]
        for role, n in sorted(buckets.items(), key=lambda kv: -kv[1])
    ]
    rows.append(["TOTAL", count(total), "100.0%"])
    rep.table(["role", "parameters", "share"], rows)

    n_exp, top_k, layers = _cfg(model)
    per_expert = buckets["experts"] // (n_exp * layers)
    active_experts = per_expert * top_k * layers
    active = active_experts + buckets["attention"] + buckets["norms"] + buckets["embed + head"] // 2

    rep.blank()
    rep.kv("experts per layer", n_exp)
    rep.kv("experts used per token", top_k)
    rep.kv("parameters in one expert", f"{per_expert / 1e6:.2f}M")
    rep.kv("total parameters", f"{total / 1e9:.3f}B")
    rep.kv("active parameters per token", f"{active / 1e9:.3f}B")
    rep.kv("active share", f"{100 * active / total:.1f}%")
    rep.takeaway(
        f"{100 * buckets['experts'] / total:.0f}% of the weights are experts, and a token "
        f"touches {top_k} of {n_exp} of them. The model is mostly a thing it "
        f"declines to use."
    )


# ---------------------------------------------------------------------------
# 2. The router
# ---------------------------------------------------------------------------


def the_router_is_tiny(rep: Report, model) -> None:
    router = [p for n, p in model.named_parameters() if ".mlp.gate." in n]
    total = sum(p.numel() for p in model.parameters())
    n_router = sum(p.numel() for p in router)
    n_exp, top_k, layers = _cfg(model)

    rep.kv("router matrices", f"{len(router)} (one per layer)")
    rep.kv("shape of each", tuple(router[0].shape))
    rep.kv("router parameters", f"{n_router / 1e6:.2f}M")
    rep.kv("as a share of the model", f"{100 * n_router / total:.3f}%")
    rep.kv("router bytes (bf16)", f"{n_router * 2 / MIB:.1f} MiB")
    # Everything that is not the router -- experts, attention, embeddings. Not
    # labelled "expert bytes": that would assert more than the number measures.
    rep.kv("everything else (bf16)", f"{(total - n_router) * 2 / GIB:.2f} GiB")
    rep.takeaway(
        "One matrix per layer, 0.03% of the parameters, decides how the other "
        "93% are spent on every token."
    )


# ---------------------------------------------------------------------------
# 3. One token, routed
# ---------------------------------------------------------------------------


@torch.no_grad()
def route(model, ids: torch.Tensor) -> torch.Tensor:
    """Router logits for every token and layer.

    Returns a ``(layers, tokens, experts)`` float32 tensor. Computed on CPU in
    float32 after the forward pass so that the printed weights do not depend on
    which backend ran the matmuls.
    """
    out = model(ids, output_router_logits=True)
    stacked = torch.stack([r.float().cpu() for r in out.router_logits])
    return stacked.reshape(stacked.shape[0], ids.shape[1], -1)


def one_token_routed(
    rep: Report, model, tok, logits: torch.Tensor, ids: torch.Tensor
) -> list[int]:
    """Walk the routing arithmetic for a single token at a single layer."""
    n_exp, top_k, layers = _cfg(model)
    # pos=1, layer=0 is chosen, not arbitrary: a reader adds the eight printed
    # weights and expects the printed total. Of the 1488 (layer, position) pairs
    # in this passage, 676 reconcile exactly at 4 decimal places and this is one
    # of them. Do not "tidy" this constant -- see the walkthrough in the post.
    pos = 1
    layer = 0
    token_text = tok.decode(ids[0, pos : pos + 1])

    row = logits[layer, pos]
    weights = torch.softmax(row, dim=-1)
    top_w, top_e = torch.topk(weights, top_k)

    rep.kv("token", f"{pos} = {token_text!r}")
    rep.kv("layer", layer)
    rep.kv("router output", f"{n_exp} logits -> softmax -> top-{top_k}")
    rep.blank()
    rep.table(
        ["rank", "expert", "logit", "softmax weight"],
        [
            [i + 1, int(e), f"{row[e]:+.4f}", f"{w:.4f}"]
            for i, (w, e) in enumerate(zip(top_w.tolist(), top_e.tolist()))
        ],
    )
    kept = top_w.sum().item()
    rep.blank()
    rep.kv(f"sum of the {top_k} kept weights", f"{kept:.4f}")
    rep.kv(f"sum of all {n_exp} weights", f"{weights.sum().item():.4f}")
    rep.kv("discarded by the top-k cut", f"{1 - kept:.4f}")
    rep.kv("renormalized? (norm_topk_prob)", model.config.norm_topk_prob)
    rep.takeaway(
        f"The kept weights sum to {kept:.4f}, not 1. OLMoE does not renormalize "
        f"after the cut, so how much probability the router left behind becomes "
        f"a scale on the layer's output."
    )
    return [int(e) for e in top_e.tolist()], kept


def routing_depth_profile(rep: Report, model, logits: torch.Tensor, tok, ids: torch.Tensor) -> None:
    """The same token's top-1 expert at every layer — routing is per layer."""
    n_exp, top_k, layers = _cfg(model)
    pos = 1
    rows = []
    for layer in range(layers):
        w = torch.softmax(logits[layer, pos], dim=-1)
        top_w, top_e = torch.topk(w, top_k)
        rows.append(
            [
                layer,
                int(top_e[0]),
                f"{top_w[0]:.4f}",
                f"{top_w.sum():.4f}",
                f"{top_w[0] / top_w.sum():.2f}",
            ]
        )
    rep.table(["layer", "top-1 expert", "its weight", "kept total", "share"], rows)
    rep.takeaway(
        "One token is routed independently at every layer, so it visits "
        f"{layers} separate committees of {top_k} on its way through the model."
    )


# ---------------------------------------------------------------------------
# 4. What the router learns
# ---------------------------------------------------------------------------


def _topk_idx(logits: torch.Tensor, top_k: int) -> torch.Tensor:
    """Chosen experts per (layer, token): ``(layers, tokens, top_k)``."""
    return torch.topk(logits, top_k, dim=-1).indices


def _usage_from_idx(idx: torch.Tensor, n_exp: int) -> torch.Tensor:
    """Per-layer expert usage distribution: (layers, experts), rows sum to 1."""
    counts = torch.zeros(idx.shape[0], n_exp)
    for layer in range(idx.shape[0]):
        counts[layer] = torch.bincount(idx[layer].reshape(-1), minlength=n_exp).float()
    return counts / counts.sum(dim=-1, keepdim=True)


def _usage(logits: torch.Tensor, top_k: int, n_exp: int) -> torch.Tensor:
    return _usage_from_idx(_topk_idx(logits, top_k), n_exp)


def _tv(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    """Total variation distance per layer. 0 = identical usage, 1 = disjoint."""
    return 0.5 * (a - b).abs().sum(dim=-1)


def what_the_router_learns(
    rep: Report, model, tok
) -> tuple[dict[str, torch.Tensor], dict[str, tuple[torch.Tensor, torch.Tensor]]]:
    """Does expert choice depend on what kind of text the token belongs to?

    A raw distance between two passages proves nothing on its own: two samples
    drawn from the *same* distribution differ too, and these passages are only a
    hundred tokens long. So this measures a noise floor first -- the distance
    between two halves of the same passage -- and reports the cross-domain
    distances against it.
    """
    n_exp, top_k, layers = _cfg(model)
    usage: dict[str, torch.Tensor] = {}
    halves: dict[str, tuple[torch.Tensor, torch.Tensor]] = {}
    rows = []
    for name, text in DOMAINS.items():
        ids = tok(text, return_tensors="pt").input_ids.to(model.device)
        idx = _topk_idx(route(model, ids), top_k)
        usage[name] = _usage_from_idx(idx, n_exp)
        mid = idx.shape[1] // 2
        halves[name] = (
            _usage_from_idx(idx[:, :mid], n_exp),
            _usage_from_idx(idx[:, mid:], n_exp),
        )
        rows.append([name, ids.shape[1]])
    rep.table(["passage", "tokens"], rows)

    floor = torch.stack([_tv(a, b) for a, b in halves.values()]).mean(dim=0)
    rep.blank()
    rep.note("Total variation distance between expert-usage distributions:")
    rep.note("0.00 = the two samples used the experts identically.")
    rep.note("The first row is the noise floor -- two halves of the SAME")
    rep.note("passage, which differ only by sampling. Read every other row")
    rep.note("against it.")
    rep.blank()

    show = [0, layers // 2, layers - 1]
    pairs = [("prose", "code"), ("prose", "math"), ("code", "math")]
    table = [
        ["same passage, split"] + [f"{floor[i]:.3f}" for i in show] + [f"{floor.mean():.3f}"]
    ]
    for a, b in pairs:
        d = _tv(usage[a], usage[b])
        table.append(
            [f"{a} vs {b}"] + [f"{d[i]:.3f}" for i in show] + [f"{d.mean():.3f}"]
        )
    rep.table(["comparison"] + [f"layer {i}" for i in show] + ["mean"], table)

    cross = torch.stack([_tv(usage[a], usage[b]) for a, b in pairs]).mean(dim=0)
    rep.blank()
    rep.kv("noise floor, mean over layers", f"{floor.mean():.3f}")
    rep.kv("cross-domain, mean over layers", f"{cross.mean():.3f}")
    rep.kv("cross-domain over noise floor", f"{cross.mean() / floor.mean():.2f}x")

    # The most domain-skewed expert in the deepest layer. Reported as two shares
    # rather than a ratio: the prose share is often exactly zero, and a ratio
    # against zero is an artifact of whatever epsilon you added, not a finding.
    last = layers - 1
    code_u, prose_u = usage["code"][last], usage["prose"][last]
    expert = int((code_u - prose_u).argmax())
    rep.blank()
    rep.kv(f"most code-leaning expert (layer {last})", expert)
    rep.kv("  share of code routing slots", f"{100 * code_u[expert]:.2f}%")
    rep.kv("  share of prose routing slots", f"{100 * prose_u[expert]:.2f}%")
    rep.kv("  an even share would be", f"{100 / n_exp:.2f}%")
    rep.kv("experts unused by prose but used by code", int(((prose_u == 0) & (code_u > 0)).sum()))

    rep.blank()
    rep.kv("noise floor, first layer", f"{floor[0]:.3f}")
    rep.kv("cross-domain, first layer", f"{cross[0]:.3f}")
    rep.kv("noise floor, last layer", f"{floor[-1]:.3f}")
    rep.kv("cross-domain, last layer", f"{cross[-1]:.3f}")
    rep.takeaway(
        f"Two halves of one passage differ by {floor.mean():.2f}; two different "
        f"kinds of text differ by {cross.mean():.2f}, "
        f"{cross.mean() / floor.mean():.1f}x as much. Expert choice tracks the "
        f"kind of text, and the gap widens with depth."
    )
    return usage, halves


# ---------------------------------------------------------------------------
# 5. The two bills
# ---------------------------------------------------------------------------


def two_bills(rep: Report, model, ids: torch.Tensor, device: torch.device) -> dict:
    """Memory is set by total parameters; time is set by active ones."""
    n_exp, top_k, layers = _cfg(model)
    total = sum(p.numel() for p in model.parameters())

    rep.kv("weights resident (bf16)", f"{total * 2 / GIB:.2f} GiB")
    rep.note("  every expert must be in memory; the router picks at run time,")
    rep.note("  so there is no subset you could have left on disk.")
    rep.blank()

    # Same weights, same memory, k changed: the cleanest isolation of "active
    # parameters" there is. Everything else about the forward pass is identical.
    # This is a timing experiment only -- with norm_topk_prob=False, routing to
    # all 64 experts changes what the model computes, so the top-64 row is a
    # measurement of cost, never of quality.
    timings = {}
    for k in (top_k, n_exp):
        model.config.num_experts_per_tok = k
        for m in model.modules():
            if hasattr(m, "top_k"):
                m.top_k = k
        with torch.no_grad():
            timings[k] = benchmark_ms(
                lambda: model(ids), device=device, warmup=2, repeats=5
            )
    model.config.num_experts_per_tok = top_k
    for m in model.modules():
        if hasattr(m, "top_k"):
            m.top_k = top_k

    active_frac = top_k / n_exp
    rep.table(
        ["experts per token", "forward (ms)", "vs top-8"],
        [
            [top_k, f"{timings[top_k]:.1f}", "1.00x"],
            [n_exp, f"{timings[n_exp]:.1f}", f"{timings[n_exp] / timings[top_k]:.2f}x"],
        ],
    )
    rep.blank()
    rep.kv("expert FLOPs ratio (64/8)", f"{n_exp / top_k:.0f}x")
    rep.kv("measured wall-clock ratio", f"{timings[n_exp] / timings[top_k]:.2f}x")
    rep.note("  below 8x because attention, norms and the LM head are unchanged")
    rep.takeaway(
        f"Turning every expert on costs {timings[n_exp] / timings[top_k]:.1f}x the time "
        f"and 0 extra bytes of weights. Memory is billed on {total / 1e9:.1f}B "
        f"parameters no matter which {top_k} get used."
    )
    return timings


# ---------------------------------------------------------------------------
# 6. Sparsity does not survive a batch
# ---------------------------------------------------------------------------


def batch_collapse(rep: Report, model, logits: torch.Tensor) -> list[tuple[int, float]]:
    """How many distinct experts a group of tokens needs, as the group grows."""
    n_exp, top_k, layers = _cfg(model)
    _, idx = torch.topk(logits, top_k, dim=-1)  # (layers, tokens, k)
    n_tokens = idx.shape[1]

    sizes = [n for n in (1, 2, 4, 8, 16, 32, 64, 128, 256) if n <= n_tokens]
    curve = []
    rows = []
    for n in sizes:
        # Average over every disjoint window of this size, so the number is not
        # an artifact of where the passage happens to start.
        per_layer = []
        for start in range(0, n_tokens - n + 1, n):
            window = idx[:, start : start + n, :]
            for layer in range(layers):
                per_layer.append(len(torch.unique(window[layer])))
        touched = sum(per_layer) / len(per_layer)
        curve.append((n, touched))
        rows.append(
            [n, f"{touched:.1f}", f"{100 * touched / n_exp:.0f}%", f"{n * top_k}"]
        )
    rep.table(
        ["tokens together", "experts needed", "of 64", "expert-slots used"], rows
    )
    rep.takeaway(
        f"One token needs {top_k} experts; {curve[-1][0]} tokens together need "
        f"{curve[-1][1]:.0f}. Sparsity is a property of a token, not of a batch — "
        f"which is why an MoE saves arithmetic but not memory."
    )
    return curve


# ---------------------------------------------------------------------------
# 7. Experts across GPUs
# ---------------------------------------------------------------------------


def experts_across_gpus(rep: Report, model, logits: torch.Tensor) -> list[tuple[int, float]]:
    """When experts are split across GPUs, how many does one token have to reach?

    Expert parallelism shards the experts, not the tokens: GPU g holds a
    contiguous block of experts, and a token whose top-k spans several GPUs has
    to be sent to each of them and its results gathered back. That is the
    all-to-all every MoE serving stack pays for, and it is measurable straight
    from the routing indices without owning a single GPU.
    """
    n_exp, top_k, layers = _cfg(model)
    idx = _topk_idx(logits, top_k)
    rows, curve = [], []
    for g in (2, 4, 8, 16):
        per_gpu = n_exp // g
        gpus = idx // per_gpu                       # which GPU each choice lands on
        hit = torch.zeros(*gpus.shape[:2], g, dtype=torch.bool)
        hit.scatter_(2, gpus, True)
        distinct = hit.sum(dim=-1).float()          # GPUs touched, per (layer, token)
        all_of_them = (distinct == g).float().mean()
        curve.append((g, distinct.mean().item()))
        rows.append(
            [
                g,
                per_gpu,
                f"{distinct.mean():.2f}",
                f"{100 * distinct.mean() / g:.0f}%",
                f"{100 * all_of_them:.0f}%",
            ]
        )
    rep.table(
        ["GPUs", "experts each", "GPUs per token", "of all", "tokens needing all"],
        rows,
    )
    rep.takeaway(
        f"Split across 8 GPUs, one token's {top_k} experts land on "
        f"{curve[2][1]:.1f} of them on average. Expert parallelism moves tokens "
        f"between GPUs, and the router decides how much."
    )
    return curve


# ---------------------------------------------------------------------------
# 8. Load balance
# ---------------------------------------------------------------------------


def load_balance(rep: Report, model, logits: torch.Tensor) -> torch.Tensor:
    n_exp, top_k, layers = _cfg(model)
    usage = _usage(logits, top_k, n_exp)
    even = 1.0 / n_exp

    rows = []
    for layer in (0, layers // 2, layers - 1):
        u = usage[layer]
        rows.append(
            [
                layer,
                f"{100 * u.max():.2f}%",
                f"{100 * u.min():.2f}%",
                f"{u.max() / even:.2f}x",
                f"{(u.std() / u.mean()):.2f}",
            ]
        )
    rep.table(
        ["layer", "busiest", "quietest", "busiest vs even", "coeff of var"], rows
    )
    rep.blank()
    rep.kv("even share would be", f"{100 * even:.2f}%")
    rep.kv("router_aux_loss_coef", model.config.router_aux_loss_coef)
    rep.kv("experts never used (last layer)", int((usage[-1] == 0).sum()))
    rep.takeaway(
        "Nothing makes the experts equally popular by construction; a balance "
        "penalty during training is what keeps one expert from swallowing the "
        "traffic and the rest from starving."
    )
    return usage


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------


def figure_block(model, chosen: list[int], theme: Theme) -> Path:
    """Where an MoE layer differs from a dense one: the MLP, replicated.

    The expert grid draws all ``n_exp`` experts and lights exactly the ``top_k``
    that the demo's own routing chose, so the picture cannot contradict the
    number in the caption.
    """
    n_exp, top_k, layers = _cfg(model)
    fig, (ax_l, ax_r) = plt.subplots(1, 2, figsize=(10.5, 5.4))

    def box(ax, x, y, w, h, label, fill, ink=None, fs=10):
        ax.add_patch(
            patches.FancyBboxPatch(
                (x, y), w, h,
                boxstyle="round,pad=0.012,rounding_size=0.02",
                linewidth=1.1, edgecolor=theme.axis, facecolor=fill,
            )
        )
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center",
                fontsize=fs, color=ink or ink_for(fill), zorder=3)

    def arrow(ax, x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle="-|>", color=theme.secondary, lw=1.3))

    for ax in (ax_l, ax_r):
        ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off"); ax.grid(False)

    # Dense block
    ax_l.set_title("Dense block", color=theme.ink)
    box(ax_l, 0.22, 0.80, 0.56, 0.10, "attention", theme.ramp[1])
    arrow(ax_l, 0.5, 0.80, 0.5, 0.66)
    box(ax_l, 0.22, 0.50, 0.56, 0.16, "one MLP\n(all tokens, every time)", theme.ramp[4])
    arrow(ax_l, 0.5, 0.50, 0.5, 0.36)
    box(ax_l, 0.22, 0.24, 0.56, 0.10, "next block", theme.ramp[0])
    ax_l.text(0.5, 0.12, "every parameter runs for every token",
              ha="center", fontsize=9.5, color=theme.secondary)

    # MoE block
    ax_r.set_title(f"MoE block ({n_exp} experts, top-{top_k})", color=theme.ink)
    box(ax_r, 0.22, 0.80, 0.56, 0.10, "attention", theme.ramp[1])
    arrow(ax_r, 0.5, 0.80, 0.5, 0.72)
    box(ax_r, 0.36, 0.62, 0.28, 0.09, "router", theme.series[1], ink="#ffffff")

    # Fan-out: stub down, then a horizontal bus, then one vertical drop into the
    # grid. Never a horizontal arrow into a box top -- that renders as a single
    # line struck through every box it passes.
    bus_y = 0.545
    ax_r.plot([0.5, 0.5], [0.62, bus_y], color=theme.secondary, lw=1.3)
    ax_r.plot([0.10, 0.90], [bus_y, bus_y], color=theme.secondary, lw=1.3)
    for x in (0.10, 0.30, 0.50, 0.70, 0.90):
        arrow(ax_r, x, bus_y, x, 0.495)

    # All 64 experts, with the 8 this demo actually routed to filled in.
    cols, rows_n = 16, n_exp // 16
    cell_w, cell_h, gap = 0.049, 0.055, 0.004
    x0 = 0.5 - (cols * cell_w + (cols - 1) * gap) / 2
    y0 = 0.46
    for e in range(n_exp):
        r, c = divmod(e, cols)
        x = x0 + c * (cell_w + gap)
        y = y0 - r * (cell_h + gap) - cell_h
        on = e in chosen
        ax_r.add_patch(
            patches.Rectangle(
                (x, y), cell_w, cell_h,
                linewidth=0.8,
                edgecolor=theme.series[1] if on else theme.axis,
                facecolor=theme.ramp[5] if on else theme.surface,
            )
        )
        if on:
            ax_r.text(x + cell_w / 2, y + cell_h / 2, str(e), ha="center",
                      va="center", fontsize=6.5, color=ink_for(theme.ramp[5]))

    grid_bottom = y0 - rows_n * (cell_h + gap)
    ax_r.text(0.5, grid_bottom - 0.03,
              f"{top_k} of {n_exp} chosen for this token · the other "
              f"{n_exp - top_k} stay resident and idle",
              ha="center", fontsize=9.5, color=theme.secondary)
    ax_r.text(0.5, grid_bottom - 0.10,
              "all parameters in memory · 17% of them multiply",
              ha="center", fontsize=9.5, color=theme.ink)

    fig.tight_layout()
    return save_both(fig, SLUG, "moe-block", theme)


def figure_architecture(model, chosen: list[int], kept: float, theme: Theme) -> Path:
    """One-page orientation diagram: whole model, one MoE layer, one expert.

    Every number on it is this post's own measurement, so the picture cannot
    drift out of agreement with the tables. Panels get their own axes rather
    than one shared coordinate space, which keeps each region's layout
    independent and stops a change in one from shifting the others.
    """
    n_exp, top_k, layers = _cfg(model)
    total = sum(p.numel() for p in model.parameters())
    hid = model.config.hidden_size
    inter = model.config.intermediate_size
    vocab = model.config.vocab_size
    per_expert = 3 * hid * inter

    fig = plt.figure(figsize=(13.5, 15.5))
    ax_stack = fig.add_axes([0.015, 0.450, 0.245, 0.470])
    ax_zoom = fig.add_axes([0.315, 0.450, 0.670, 0.470])
    ax_exp = fig.add_axes([0.015, 0.020, 0.270, 0.375])
    ax_num = fig.add_axes([0.345, 0.020, 0.290, 0.375])
    ax_step = fig.add_axes([0.695, 0.020, 0.290, 0.375])
    for ax in (ax_stack, ax_zoom, ax_exp, ax_num, ax_step):
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")
        ax.grid(False)

    def box(ax, x, y, w, h, label, fill, fs=9.5, ink=None, lw=1.1, ec=None):
        ax.add_patch(patches.FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.008,rounding_size=0.02",
            linewidth=lw, edgecolor=ec or theme.axis, facecolor=fill, zorder=2))
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center",
                fontsize=fs, color=ink or ink_for(fill), zorder=3, linespacing=1.45)

    def down(ax, x, y1, y2):
        ax.annotate("", xy=(x, y2), xytext=(x, y1), zorder=1,
                    arrowprops=dict(arrowstyle="-|>", color=theme.secondary, lw=1.2))

    def panel(ax, title):
        ax.add_patch(patches.FancyBboxPatch(
            (0.005, 0.005), 0.99, 0.99, boxstyle="round,pad=0.006,rounding_size=0.03",
            linewidth=1.0, edgecolor=theme.axis, facecolor="none", zorder=0))
        ax.text(0.5, 0.955, title, ha="center", va="center",
                fontsize=11.5, fontweight="bold", color=theme.ink)

    # ---- left: the whole model -------------------------------------------
    ax_stack.text(0.5, 0.985, "The whole model", ha="center", fontsize=11.5,
                  fontweight="bold", color=theme.ink)
    ax_stack.text(0.5, 0.938, "input text", ha="center", fontsize=9.5,
                  color=theme.secondary)
    down(ax_stack, 0.5, 0.924, 0.892)
    box(ax_stack, 0.06, 0.832, 0.88, 0.060,
        "token embedding\n({:,} -> {:,})".format(vocab, hid), theme.ramp[1])
    down(ax_stack, 0.5, 0.832, 0.800)

    ax_stack.add_patch(patches.FancyBboxPatch(
        (0.02, 0.318), 0.96, 0.482, boxstyle="round,pad=0.006,rounding_size=0.02",
        linewidth=1.1, edgecolor=theme.muted, facecolor="none",
        linestyle=(0, (4, 3)), zorder=1))
    ax_stack.text(0.5, 0.770, "{} × transformer layer".format(layers),
                  ha="center", fontsize=9.5, style="italic", color=theme.secondary)
    box(ax_stack, 0.07, 0.652, 0.86, 0.092,
        "self-attention + RoPE\n(dense: every token\nuses all of it)", theme.ramp[1], fs=9)
    down(ax_stack, 0.5, 0.652, 0.620)
    box(ax_stack, 0.07, 0.462, 0.86, 0.158,
        "MoE feed-forward\n\n{} experts\ntop-{} per token\n\n(sparse)".format(n_exp, top_k),
        theme.series[1], ink="#ffffff", fs=9, lw=2.0, ec=theme.series[1])
    down(ax_stack, 0.5, 0.462, 0.412)
    for dy in (0.0, 0.020, 0.040):
        ax_stack.plot([0.5], [0.348 + dy], marker="o", markersize=2.2,
                      color=theme.muted, zorder=3)
    down(ax_stack, 0.5, 0.310, 0.272)
    box(ax_stack, 0.06, 0.212, 0.88, 0.060, "final norm", theme.ramp[0])
    down(ax_stack, 0.5, 0.212, 0.180)
    box(ax_stack, 0.06, 0.104, 0.88, 0.076,
        "LM head\n({:,} -> {:,})".format(hid, vocab), theme.ramp[1])
    down(ax_stack, 0.5, 0.104, 0.072)
    ax_stack.text(0.5, 0.042, "next-token probabilities", ha="center",
                  fontsize=9.5, color=theme.secondary)

    # ---- right: one MoE layer, zoomed ------------------------------------
    ax_zoom.add_patch(patches.FancyBboxPatch(
        (0.005, 0.005), 0.99, 0.99, boxstyle="round,pad=0.006,rounding_size=0.02",
        linewidth=1.6, edgecolor=theme.series[1], facecolor="none", zorder=0))
    ax_zoom.text(0.5, 0.958, "One MoE feed-forward layer, in detail",
                 ha="center", fontsize=11.5, fontweight="bold", color=theme.ink)

    box(ax_zoom, 0.030, 0.812, 0.195, 0.078,
        "input from\nattention\n({:,})".format(hid), theme.ramp[0], fs=8.8)
    ax_zoom.annotate("", xy=(0.320, 0.851), xytext=(0.232, 0.851),
                     arrowprops=dict(arrowstyle="-|>", color=theme.secondary, lw=1.2))
    box(ax_zoom, 0.320, 0.806, 0.235, 0.090,
        "router\n{} × {:,} linear,\nthen softmax".format(n_exp, hid),
        theme.series[1], ink="#ffffff", fs=8.8)
    ax_zoom.annotate("", xy=(0.650, 0.851), xytext=(0.562, 0.851),
                     arrowprops=dict(arrowstyle="-|>", color=theme.secondary, lw=1.2))
    box(ax_zoom, 0.650, 0.803, 0.320, 0.096,
        "one score per expert, {} of them.\nkeep the top {}, discard the rest".format(n_exp, top_k),
        theme.ramp[0], fs=8.8)

    down(ax_zoom, 0.4375, 0.806, 0.768)
    ax_zoom.plot([0.115, 0.885], [0.768, 0.768], color=theme.secondary, lw=1.2)
    for x in (0.115, 0.30, 0.50, 0.70, 0.885):
        down(ax_zoom, x, 0.768, 0.720)

    cols = 16
    cw, ch, gap = 0.0475, 0.050, 0.0045
    x0 = 0.5 - (cols * cw + (cols - 1) * gap) / 2
    y0 = 0.708
    for e in range(n_exp):
        r, c = divmod(e, cols)
        x = x0 + c * (cw + gap)
        y = y0 - r * (ch + gap) - ch
        on = e in chosen
        ax_zoom.add_patch(patches.Rectangle(
            (x, y), cw, ch, linewidth=0.8, zorder=2,
            edgecolor=theme.series[1] if on else theme.axis,
            facecolor=theme.ramp[5] if on else theme.surface))
        if on:
            ax_zoom.text(x + cw / 2, y + ch / 2, str(e), ha="center", va="center",
                         fontsize=6.5, color=ink_for(theme.ramp[5]), zorder=3)
    gb = y0 - (n_exp // cols) * (ch + gap)
    ax_zoom.text(0.5, gb - 0.032,
                 "{} experts run  ·  {} are skipped, and stay in memory either way".format(
                     top_k, n_exp - top_k),
                 ha="center", fontsize=9.5, color=theme.secondary)

    down(ax_zoom, 0.5, gb - 0.058, gb - 0.108)
    box(ax_zoom, 0.275, gb - 0.212, 0.45, 0.104,
        "weighted combination\nadd the {} outputs, each scaled\nby its own router score".format(top_k),
        theme.ramp[4], fs=8.8)
    down(ax_zoom, 0.5, gb - 0.212, gb - 0.258)
    ax_zoom.text(0.5, gb - 0.288,
                 "output to the next layer ({:,})".format(hid),
                 ha="center", fontsize=9.5, color=theme.secondary)
    ax_zoom.text(0.5, gb - 0.360,
                 "the {} kept scores sum to {:.4f}, not 1 — OLMoE does not renormalize\n"
                 "after the cut, so that shortfall scales this layer's output".format(top_k, kept),
                 ha="center", fontsize=9, color=theme.ink, linespacing=1.5)

    # ---- bottom left: inside one expert ----------------------------------
    panel(ax_exp, "What is inside one expert?")
    steps = [
        ("input ({:,})".format(hid), theme.ramp[0], 0.068),
        ("gate -> {:,}    up -> {:,}\n(two linears, side by side)".format(inter, inter),
         theme.ramp[1], 0.100),
        ("SiLU on gate, multiply by up\n(that pairing is SwiGLU)", theme.ramp[2], 0.100),
        ("down -> {:,}\n(one linear, back down)".format(hid), theme.ramp[1], 0.100),
        ("output ({:,})".format(hid), theme.ramp[0], 0.068),
    ]
    y = 0.858
    for i, (label, fill, h) in enumerate(steps):
        box(ax_exp, 0.07, y - h, 0.86, h, label, fill, fs=8.6)
        if i < len(steps) - 1:
            down(ax_exp, 0.5, y - h, y - h - 0.040)
        y -= h + 0.040
    ax_exp.text(0.5, 0.092,
                "an ordinary feed-forward network —\nthe same one a dense model has, "
                "built {} times per layer.\n{:.2f}M parameters each.".format(n_exp, per_expert / 1e6),
                ha="center", fontsize=8.6, color=theme.secondary, linespacing=1.6)

    # ---- bottom middle: the numbers --------------------------------------
    panel(ax_num, "Key numbers, all measured here")
    rows = [
        ("total parameters", "{:.3f}B".format(total / 1e9)),
        ("active per token", "1.177B   (17.0%)"),
        ("layers", "{}".format(layers)),
        ("experts per layer", "{}".format(n_exp)),
        ("experts per token", "{}".format(top_k)),
        ("parameters per expert", "{:.2f}M".format(per_expert / 1e6)),
        ("weights that are experts", "93.1%"),
        ("weights that are router", "0.030%"),
        ("resident in bf16", "12.89 GiB"),
        ("experts for 1 token", "{}".format(top_k)),
        ("experts for 256 tokens", "60.9"),
    ]
    y = 0.858
    for label, value in rows:
        ax_num.text(0.06, y, label, ha="left", va="center", fontsize=9,
                    color=theme.secondary)
        ax_num.text(0.94, y, value, ha="right", va="center", fontsize=9,
                    fontweight="bold", color=theme.ink)
        y -= 0.0705
    ax_num.plot([0.06, 0.94], [y + 0.034, y + 0.034], color=theme.axis, lw=0.8)
    ax_num.text(0.5, y - 0.012, "OLMoE-1B-7B · bfloat16 · Apple M4",
                ha="center", fontsize=8.5, color=theme.muted)

    # ---- bottom right: the walk-through ----------------------------------
    panel(ax_step, "What happens to one token")
    walk = [
        "It goes through self-attention,\nexactly as in a dense model.",
        "The router scores all {} experts\nfrom the token's own vector.".format(n_exp),
        "Softmax, then keep the top {}.\nThe other {} are skipped.".format(top_k, n_exp - top_k),
        "Those {} experts run, in parallel.\nEach is an ordinary FFN.".format(top_k),
        "Their outputs are added, each\nscaled by its router score.",
        "On to the next layer, which\nroutes it again, independently.",
    ]
    y = 0.862
    for i, text in enumerate(walk, start=1):
        ax_step.add_patch(patches.Circle((0.11, y), 0.030, facecolor=theme.series[0],
                                         edgecolor="none", zorder=3))
        ax_step.text(0.11, y, str(i), ha="center", va="center", fontsize=9,
                     fontweight="bold", color=ink_for(theme.series[0]), zorder=4)
        ax_step.text(0.195, y, text, ha="left", va="center", fontsize=8.6,
                     color=theme.ink, linespacing=1.6)
        y -= 0.126
    ax_step.text(0.5, 0.048,
                 "The capacity of {:.1f}B parameters,\nthe arithmetic of 1.2B,\n"
                 "and the memory bill of all {:.1f}B.".format(total / 1e9, total / 1e9),
                 ha="center", fontsize=8.8, color=theme.secondary, linespacing=1.6)

    fig.suptitle("Mixture-of-Experts, end to end", fontsize=16, fontweight="bold",
                 color=theme.ink, y=0.976)
    fig.text(0.5, 0.950,
             "OLMoE-1B-7B — every number on this page is measured in this post",
             ha="center", fontsize=10.5, color=theme.secondary)
    return save_both(fig, SLUG, "moe-architecture", theme)


def figure_router_flow(model, logits: torch.Tensor, theme: Theme,
                       layer: int = 0, pos: int = 1) -> Path:
    """The router as a shape walkthrough, then the same token's real numbers.

    The top row is the pipeline in tensor shapes, which is the form post 1 used
    for attention. The bottom is all 64 probabilities for one actual token, so
    the reader can see *why* the kept mass is a fraction rather than being told.
    """
    n_exp, top_k, layers = _cfg(model)
    hid = model.config.hidden_size
    row = logits[layer, pos]
    probs = torch.softmax(row, dim=-1)
    top_w, top_e = torch.topk(probs, top_k)
    kept = top_w.sum().item()

    fig = plt.figure(figsize=(12.5, 8.2))
    ax_flow = fig.add_axes([0.02, 0.575, 0.96, 0.355])
    ax_bar = fig.add_axes([0.075, 0.085, 0.895, 0.405])
    for ax in (ax_flow, ax_bar):
        ax.grid(False)
    ax_flow.set_xlim(0, 1); ax_flow.set_ylim(0, 1); ax_flow.axis("off")

    def grid(ax, cx, cy, cols, rows_n, w, h, fill, edge=None):
        cw, chh = w / cols, h / rows_n
        for r in range(rows_n):
            for c in range(cols):
                ax.add_patch(patches.Rectangle(
                    (cx - w / 2 + c * cw, cy + h / 2 - (r + 1) * chh), cw, chh,
                    linewidth=0.6, edgecolor=edge or theme.axis, facecolor=fill, zorder=2))

    def caption(ax, cx, title, shape, y_title=0.325, y_shape=0.255):
        ax.text(cx, y_title, title, ha="center", fontsize=10,
                fontweight="bold", color=theme.ink)
        ax.text(cx, y_shape, shape, ha="center", va="top", fontsize=9,
                color=theme.secondary, linespacing=1.5)

    def op(ax, x1, x2, label, sub):
        y = 0.60
        ax.annotate("", xy=(x2, y), xytext=(x1, y),
                    arrowprops=dict(arrowstyle="-|>", color=theme.secondary, lw=1.3))
        mid = (x1 + x2) / 2
        ax.text(mid, y + 0.115, label, ha="center", fontsize=9.5,
                fontweight="bold", color=theme.series[1])
        ax.text(mid, y + 0.035, sub, ha="center", fontsize=8.5, color=theme.secondary)

    xs = [0.085, 0.375, 0.665, 0.925]
    grid(ax_flow, xs[0], 0.60, 6, 4, 0.105, 0.30, theme.ramp[1])
    caption(ax_flow, xs[0], "token vectors", f"(n × {hid:,})")
    op(ax_flow, xs[0] + 0.075, xs[1] - 0.095, "router matrix",
       f"{hid:,} -> {n_exp}, one score per expert")
    grid(ax_flow, xs[1], 0.60, 8, 4, 0.135, 0.30, theme.ramp[2])
    caption(ax_flow, xs[1], "routing logits", f"(n × {n_exp})   raw scores")
    op(ax_flow, xs[1] + 0.09, xs[2] - 0.095, "softmax",
       f"over all {n_exp}, each row sums to 1")
    grid(ax_flow, xs[2], 0.60, 8, 4, 0.135, 0.30, theme.ramp[4])
    caption(ax_flow, xs[2], "routing probabilities", f"(n × {n_exp})")
    op(ax_flow, xs[2] + 0.09, xs[3] - 0.055, f"keep top {top_k}",
       "discard the rest")
    grid(ax_flow, xs[3], 0.60, 2, 4, 0.045, 0.30, theme.ramp[5])
    caption(ax_flow, xs[3], "chosen experts", f"(n × {top_k})\n+ their weights")

    ax_flow.text(0.5, 0.965, "How the router picks, in shapes",
                 ha="center", fontsize=12.5, fontweight="bold", color=theme.ink)
    ax_flow.text(0.5, 0.895, "n is however many tokens are being processed together; "
                 "every row is routed independently",
                 ha="center", fontsize=9, color=theme.secondary)

    # ---- the same thing, for one real token ------------------------------
    keep = set(int(e) for e in top_e.tolist())
    colors = [theme.ramp[5] if e in keep else theme.ramp[1] for e in range(n_exp)]
    ax_bar.bar(range(n_exp), probs.numpy() * 100, color=colors, width=0.78,
               edgecolor="none")
    ax_bar.set_xlim(-1, n_exp)
    ax_bar.set_xlabel(f"expert (layer {layer})", color=theme.secondary)
    ax_bar.set_ylabel("routing probability (%)", color=theme.secondary)
    ax_bar.set_title(
        f"All {n_exp} probabilities for one token, and the {top_k} that survive the cut",
        color=theme.ink)
    for s in ("top", "right"):
        ax_bar.spines[s].set_visible(False)
    ax_bar.spines["left"].set_color(theme.axis)
    ax_bar.spines["bottom"].set_color(theme.axis)
    ax_bar.tick_params(colors=theme.muted)
    for lbl in ax_bar.get_xticklabels() + ax_bar.get_yticklabels():
        lbl.set_color(theme.secondary)
    ax_bar.set_axisbelow(True)
    ax_bar.yaxis.grid(True, color=theme.grid, linewidth=0.8)

    # annotate the kept mass, placed on whichever side has room
    hi = int(top_e[0])
    side = "left" if hi > n_exp / 2 else "right"
    tx = hi - 6 if side == "left" else hi + 6
    ax_bar.annotate(
        f"kept: {kept:.4f}\ndiscarded: {1 - kept:.4f}",
        xy=(hi, float(probs[hi]) * 100), xytext=(tx, float(probs[hi]) * 100 * 0.92),
        ha="right" if side == "left" else "left", va="top", fontsize=9.5,
        color=theme.ink,
        arrowprops=dict(arrowstyle="-", color=theme.axis, lw=0.9))
    ax_bar.text(0.985, 0.90,
                f"the {top_k} kept weights are NOT rescaled to sum to 1",
                transform=ax_bar.transAxes, ha="right", fontsize=9,
                color=theme.secondary)
    return save_both(fig, SLUG, "router-flow", theme)


def figure_where_the_weights_are(rep_counts: dict, theme: Theme) -> Path:
    """Ink measures the quantity: one bar, split by role."""
    fig, ax = plt.subplots(figsize=(9.5, 2.9))
    total = sum(rep_counts.values())
    order = sorted(rep_counts.items(), key=lambda kv: -kv[1])
    small = [r for r, n in order if 100 * n / total <= 8]
    left = 0.0
    for i, (role, n) in enumerate(order):
        share = 100 * n / total
        fill = theme.ramp[5] if role == "experts" else theme.ramp[max(0, 3 - i)]
        ax.barh([0], [share], left=[left], height=0.55, color=fill,
                edgecolor=theme.surface, linewidth=1.2)
        if share > 8:
            ax.text(left + share / 2, 0, f"{role}\n{share:.1f}%", ha="center",
                    va="center", fontsize=11, color=ink_for(fill))
        else:
            # Too narrow to label inside, and every small segment is crowded into
            # the last few percent of the bar -- so labels go on a spread-out row
            # below with a leader back to the segment they name.
            pct = f"{share:.1f}%" if share >= 0.1 else f"{share:.3f}%"
            slot = small.index(role)
            label_x = 34 + 22 * slot
            y_txt = -0.62 if slot % 2 == 0 else -0.95
            ax.annotate(
                f"{role}  {pct}",
                xy=(left + share / 2, -0.30),
                xytext=(label_x, y_txt),
                ha="center", va="center", fontsize=9, color=theme.secondary,
                arrowprops=dict(arrowstyle="-", color=theme.axis, lw=0.8,
                                shrinkA=2, shrinkB=2),
            )
        left += share
    ax.set_xlim(0, 100); ax.set_ylim(-1.25, 0.45)
    ax.set_yticks([]); ax.set_xlabel("share of all parameters (%)")
    ax.grid(False)
    for s in ("left", "right", "top"):
        ax.spines[s].set_visible(False)
    ax.set_title("Where OLMoE-1B-7B's 6.9B parameters live", color=theme.ink)
    fig.tight_layout()
    return save_both(fig, SLUG, "weight-census", theme)


def figure_specialization(
    usage: dict[str, torch.Tensor],
    halves: dict[str, tuple[torch.Tensor, torch.Tensor]],
    theme: Theme,
) -> Path:
    """Expert usage per domain in the last layer — the specialization claim.

    The top two rows are the two halves of the *same* prose passage. They are
    what sampling noise looks like, and they are in the figure so the reader can
    tell the cross-domain rows apart from it by eye rather than on trust.
    """
    from ..plotting import sequential_cmap

    last = usage["prose"].shape[0] - 1
    rows = [
        ("prose, 1st half", halves["prose"][0][last]),
        ("prose, 2nd half", halves["prose"][1][last]),
        ("code", usage["code"][last]),
        ("math", usage["math"][last]),
    ]
    names = [n for n, _ in rows]
    data = torch.stack([v for _, v in rows]).numpy()

    fig, ax = plt.subplots(figsize=(10.5, 3.3))
    im = ax.imshow(data * 100, aspect="auto", cmap=sequential_cmap(theme),
                   interpolation="nearest")
    ax.set_yticks(range(len(names)), names)
    # Separate the noise-floor pair from the cross-domain rows.
    ax.axhline(1.5, color=theme.surface, lw=3.0)
    ax.set_xlabel(f"expert (layer {last})")
    ax.set_title("The same 64 experts, used differently by different text",
                 color=theme.ink)
    ax.axhline(1.5, color=theme.ink, lw=1.0)
    ax.grid(False)
    cb = fig.colorbar(im, ax=ax, pad=0.015)
    cb.set_label("% of that passage's routing slots", color=theme.secondary)
    cb.ax.tick_params(colors=theme.muted)
    cb.outline.set_visible(False)
    fig.tight_layout()
    return save_both(fig, SLUG, "specialization", theme)


def figure_batch_collapse(curve: list[tuple[int, float]], n_exp: int, theme: Theme) -> Path:
    """Experts needed against tokens processed together."""
    fig, ax = plt.subplots(figsize=(8.5, 4.6))
    xs = [c[0] for c in curve]
    ys = [c[1] for c in curve]
    ax.axhline(n_exp, color=theme.muted, lw=1.2, ls="--")
    ax.text(xs[0], n_exp - 2.5, f"all {n_exp} experts", fontsize=9.5,
            color=theme.secondary, va="top")
    ax.plot(xs, ys, marker="o", color=theme.series[0], label="experts actually needed")
    ax.plot(xs, [min(n_exp, 8 * x) for x in xs], marker="", ls=":",
            color=theme.series[1], label="if no two tokens ever agreed")
    ax.set_xscale("log", base=2)
    ax.set_xticks(xs, [str(x) for x in xs])
    ax.set_xlabel("tokens processed together")
    ax.set_ylabel("distinct experts required")
    ax.set_ylim(0, n_exp + 6)
    ax.set_title("Per-token sparsity does not survive batching", color=theme.ink)
    ax.legend(labelcolor=theme.secondary)
    fig.tight_layout()
    return save_both(fig, SLUG, "batch-collapse", theme)


def make_figures(
    rep: Report, model, counts: dict, usage: dict, halves: dict,
    curve: list, chosen: list[int], kept: float, logits: torch.Tensor,
) -> None:
    n_exp, _, _ = _cfg(model)
    written = []
    for theme in THEMES:
        with styled(theme):
            written.append(figure_architecture(model, chosen, kept, theme))
            written.append(figure_block(model, chosen, theme))
            written.append(figure_router_flow(model, logits, theme))
            written.append(figure_where_the_weights_are(counts, theme))
            written.append(figure_specialization(usage, halves, theme))
            written.append(figure_batch_collapse(curve, n_exp, theme))
    for path in written:
        rep.note(f"wrote {path.relative_to(path.parents[2])}")


# ---------------------------------------------------------------------------


def main() -> None:
    torch.manual_seed(0)
    rep = Report("05", "Mixture-of-experts: routing, and what sparsity costs")
    rep.header()

    device = get_device()
    model = _load(device)
    tok = _tokenizer()
    n_exp, top_k, layers = _cfg(model)

    ids = tok(PROSE, return_tensors="pt").input_ids.to(device)
    rep.kv("model", MODEL)
    rep.kv("layers", layers)
    rep.kv("experts per layer", n_exp)
    rep.kv("experts per token", top_k)
    rep.kv("dtype", "bfloat16")
    rep.kv("routing passage", f"{ids.shape[1]} tokens")

    counts = {"experts": 0, "router": 0, "attention": 0, "embed + head": 0, "norms": 0}
    for name, p in model.named_parameters():
        n = p.numel()
        if ".experts." in name:
            counts["experts"] += n
        elif ".mlp.gate." in name:
            counts["router"] += n
        elif ".self_attn." in name:
            counts["attention"] += n
        elif "embed_tokens" in name or "lm_head" in name:
            counts["embed + head"] += n
        else:
            counts["norms"] += n

    rep.section("1. Where the parameters actually are               [post §1]")
    where_the_parameters_are(rep, model)

    rep.section("2. The router is the smallest part of the model    [post §2]")
    the_router_is_tiny(rep, model)

    logits = route(model, ids)

    rep.section("3. One token, routed                               [post §3]")
    chosen, kept = one_token_routed(rep, model, tok, logits, ids)
    rep.blank()
    routing_depth_profile(rep, model, logits, tok, ids)

    rep.section("4. What the router learns                          [post §4]")
    usage, halves = what_the_router_learns(rep, model, tok)

    rep.section("5. Two bills: memory and time                      [post §5]")
    two_bills(rep, model, ids, device)

    # Sections 6 and 7 both climb with sample size, so they get a longer
    # passage: on 94 tokens they would report a property of the passage.
    long_ids = tok(LONG_PROSE, return_tensors="pt").input_ids.to(device)
    long_logits = route(model, long_ids)

    rep.section("6. Sparsity does not survive a batch               [post §6]")
    rep.kv("passage", f"{long_ids.shape[1]} tokens")
    rep.blank()
    curve = batch_collapse(rep, model, long_logits)

    rep.section("7. Experts across GPUs                             [post §7]")
    rep.kv("passage", f"{long_ids.shape[1]} tokens")
    rep.blank()
    experts_across_gpus(rep, model, long_logits)

    rep.section("8. Nothing balances the load for free              [post §8]")
    rep.kv("passage", f"{long_ids.shape[1]} tokens")
    rep.kv("routing slots per layer", f"{long_ids.shape[1] * top_k}")
    rep.blank()
    load_balance(rep, model, long_logits)

    rep.section("9. Figures")
    make_figures(rep, model, counts, usage, halves, curve, chosen, kept, logits)


if __name__ == "__main__":
    main()
